### ISSUE TITLE
Could not find window id

### ISSUE THREAD

**Issue by 2b-t** [awesomebytes/rqt_embed_window#1]
First of all *thanks a lot for your effort*. The possibility of having access to other applications inside `rqt` sounds intriguing but initially I couldn't get it to work as it is not mentioned explicitly that you need `wmctrl` for it to work.

After having entered the `Qt GUI command to execute (disable splashscreen)` it always brings up another dialog box `If you prefer to find the window by the window name, input it here` and then no matter what I'd input there it would launch the application in a different window,

![image](https://user-images.githubusercontent.com/53856473/122760422-64edc500-d29b-11eb-8620-4db96c0f0881.png)

run for a couple of seconds, then close that window outputting 

```
[ERROR] [1624277439.772656]: Could not find window id...
[ERROR] [1624277439.777458]: Command was: rviz -s None
Window name was: ''
StdOut was:
StdErr was: QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setPen: Painter not active
```

to the console. Furthermore when launching the `test_if_window_can_be_embedded.py` script it would terminate with

`subprocess.CalledProcessError: Command 'wmctrl -lp' returned non-zero exit status 127`.

This **can be resolved by installing `wmctrl`**

`$ sudo apt-get install wmctrl`

**Comment by 2b-t** [comment]
This problem can be resolved by installing [`wmctrl`](https://linux.die.net/man/1/wmctrl) with

`$ sudo apt-get install wmctrl`

**Comment by awesomebytes** [comment]
I'm glad you found the solution! The package actually depends in `package.xml` to wmctrl, I guess that when I get to release the package, and people can just `apt-get install` it, this will not happen again. Thanks for your kind comments, though!

**Comment by 2b-t** [comment]
@awesomebytes Oh, sorry, I missed that one. So actually `$ rosdep install rqt_embed_window` would have solved it as well!
